---
title: "Xtra lit review"
author: "Andy Krause"
date: "11/11/2019"
output: html_document
---
 
 
### House Price Index Methods


### Model Agnostic Interpretability Methods

* Direct readers to seminal RF work



<!-- Yen Min Goh, Greg Costello & Greg Schwann (2012) Accuracy and Robustness of House Price Index Methods, Housing Studies, 27:5, 643-666, DOI: 10.1080/02673037.2012.697551 -->


<!-- Englund Quigley Redfearn (1999) “The choice of methodology for computing housing price indexes: Comparisons of temporal aggregation and sample definition” (JREFE) -->

<!-- Diewert Heravi Silver (2007) “Hedonic imputation versus time dummy hedonic indexes” InternationalMonetary Fund Working Paper No. 07/234. -->

<!-- Revision Cit(Clapp and Giacotto 1999; Bourassa, Hoesli and Sun 2006; Deng and Quigley 2008; Clapham et al 2006) -->

<!-- @article{bourassa2006simple, -->
<!--   title={A simple alternative house price index method}, -->
<!--   author={Bourassa, Steven C and Hoesli, Martin and Sun, Jian}, -->
<!--   journal={Journal of Housing Economics}, -->
<!--   volume={15}, -->
<!--   number={1}, -->
<!--   pages={80--97}, -->
<!--   year={2006}, -->
<!--   publisher={Elsevier} -->
<!-- } -->

<!-- @article{clapham2006revisiting, -->
<!--   title={Revisiting the past and settling the score: index revision for house price derivatives}, -->
<!--   author={Clapham, Eric and Englund, Peter and Quigley, John M and Redfearn, Christian L}, -->
<!--   journal={Real Estate Economics}, -->
<!--   volume={34}, -->
<!--   number={2}, -->
<!--   pages={275--302}, -->
<!--   year={2006}, -->
<!--   publisher={Wiley Online Library} -->
<!-- } -->

<!-- @article{deng2008index, -->
<!--   title={Index revision, house price risk, and the market for house price derivatives}, -->
<!--   author={Deng, Yongheng and Quigley, John M}, -->
<!--   journal={The Journal of Real Estate Finance and Economics}, -->
<!--   volume={37}, -->
<!--   number={3}, -->
<!--   pages={191--209}, -->
<!--   year={2008}, -->
<!--   publisher={Springer} -->
<!-- } -->

<!-- @article{clapp1999revisions, -->
<!--   title={Revisions in repeat-sales price indexes: here today, gone tomorrow?}, -->
<!--   author={Clapp, John M and Giaccotto, Carmelo}, -->
<!--   journal={Real Estate Economics}, -->
<!--   volume={27}, -->
<!--   number={1}, -->
<!--   pages={79--104}, -->
<!--   year={1999}, -->
<!--   publisher={Wiley Online Library} -->
<!-- } -->


**<<<<CUT LINE>>>>**




Studies comparing various indexing method were popular in the 1980s and 1990s (Mark & Goldberg 1984; Case et al 1991; Clapp et al 1991; Crone & Voith 1992; Gatzlaff & Ling 1994; Meese & Wallace 1997).  In most cases, work published during this period compared indexes generated with some permutation of repeat sale, hedonic, median/mean, assessed/appraised value and/or hybrid methods.  The results suggest little agreement in terms of the preferred method, though the median/mean based methods used in industry are generally shown to be less reliable (Mark & Goldberg 1984; Crone & Voith 1992; Meese & Wallace 1997). Clapp et al. (1991) suggest that the hedonic method may outperform repeat sales models in short time periods, while a more recent study by Nagaraja et al. (2014) show better results from a hybrid, autoregressive model (expanding on Case & Quigley (1991)) than from more traditional repeat sales models. Dorsey et al. (2010) show substantively different results between hedonic and repeat sales models in identifying the peak of the market during the housing boom of the mid-2000s. Common across all studies, but most explicitly made by Case et al (1991), are discussions of the various shortcomings and issues that plague each model type.

Out of this arose a suite of research that set out to catalog, measure and, often, correct for the issues identified in the earliest comparative work.  The most commonly addressed issue is that of sample selection bias (Abraham & Schauman 1991; Haurin & Henderschott 1991; Clapp et al 1992; Case et al 1997;  Steele & Goy 1997; Gatzlaff & Haurin 1997, 1998; Munneke & Slade 2000), an issue affecting nearly all of the available models.  Issues stemming from the necessity to revise indexes over time, especially in the case of repeat sales models, have received attention in the literature (Clapp & Giacotto 1999; Butler et al 2005; Clapham et al 2006; Deng & Quigley 2008). Property age and depreciation and the biases associated with it have also been raised and methods presented to control for it have been offered (Goodman & Thibodeau 1997; Cannaday et al 2005; Chau et al 2005). Adding to the list of biases are potential problems arising from seller reservation bias (Goetzmann & Peng 2006) and submarket (or product) aggregation bias (Guttery and Sirmans 1998).

A related set of work tackles issues stemming from the treatment of time in the various price indexing models.  In short, the aggregation of time periods required to keep per period sample sizes high enough may create biased results (Englund et al 1999; Dreiman & Pennington-Cross 2004). As may the assumption in standard hedonic approach of time-consistent coefficients for the non-temporal independent variables (Knight et al. 1995, Zabel 1999).  To combat violations of the temporally stability in coefficient estimates a number of time-varying parameters approaches have been proposed and tested (Knight et al 1995; Zabel 1999; Munneke & Slade 2001, Clapham et al. 2006).  Alternative time parametizations have, likewise, been presented to provide alternatives to excessive temporal aggregation (Schwann 1998; McMillen & Dombrow 2001, Bokhari & Geltner 2012).

Studies addressing spatial dependence in the models represent a final set of issues that have been raised (Can & Megbolugbe 1997; Gelfand et al 2004; Tu et al 2004; Nappi-Choulet & Maury 2009; Dorsey et al 2010).  The primary goal here is to improve the model estimates, and therefore, the index values, by better accounting for the inherent spatial structure of housing markets.

A third category of research aims are those dealing with indexes for submarkets.  In this context submarkets can be strictly geographic (Goodman 1978; Hill et al 1997; Gunterman et al 2016) or non-spatial in nature, based on price quantiles or housing product -- 2 bedroom vs 3 bedroom, for example. (Pollakowski et al 1991; Guttery & Sirmans 1998; McMillen & Thorsnes 2006; Coulson & McMillen 2007; Jansen et al 2008; Prasad & Richards 2009).  The most straightforward approach to dealing with submarkets involves simply segmenting the data by submarket definition (geographic or otherwise) and using an established method to generate an index.  More complex methods have been proposed as well.  These primarily include the use of weighting observations to better match the submarket for which the index is being generated (Meese & Wallace 1991; Goetzmann & Spiegel 1997; McMillen 2003; Clapp 2004; Jansen et al 2008).  Spatially weighted approaches like the semi-parameteric method proposed by Clapp (2004) allow for a 'surface' of price indexes to be created that vary continuously over space.

A final set of work present novel improvements to existing data generation, models or estimators. The first and most common are those presenting hybrid hedonic and repeat sales models aimed at capturing the benefits and negating the shortcomings of both individual model types (Case & Quigley 1991; Quigley 1995; Hill et al 1997; Englund et al. 1998, Nagaraja et al 2014; Guntermann et al 2016).  A number of more recent improvements have been offered to create pseudo-repeat sales (McMillen 2012; Guo et al 2014), estimate robust statistical models (Bourassa et al 2013; Bourassa et al 2016), produced chained indexes (Clapham et al 2006) and address small samples sizes with a frequency conversion method (Bokhari & Geltner 2012; Bourassa & Hoesli 2016).

The existing literature on house price index creation is broad and ventures into most directions taken by standard, inferential statistics.  What is lacking are attempts to leverage the growing body of machine learning models and techniques to understand real estate price movements over time.  This study presents a first attempt at using interpretable methods on top of machine learning models to do so along with a software package to aid in reproduction and extension of this approach. 
